import { getUserWithUsername, postToJSON } from "../../lib/firebase";
import {
  query,
  collection,
  where,
  getDocs,
  getFirestore,
} from "firebase/firestore";
import UserProfile from "../../components/UserProfile";
import PostFeed from "../../components/PostFeed";
import Navbar from "../../components/Navbar";
import Head from "next/head";

export async function getServerSideProps({ query: urlQuery }) {
  const { username } = urlQuery;

  const userDoc = await getUserWithUsername(username);

  if (!userDoc) {
    return {
      notFound: true,
    };
  }
  let user = null;
  let posts = null;
  if (userDoc) {
    user = userDoc.data();
    const postsQuery = query(
      collection(getFirestore(), userDoc.ref.path, "Rezerwacje"),
      where("dataWyjazdu", "!=", null)
    );
    posts = (await getDocs(postsQuery)).docs.map((e) => postToJSON(e));
  }
  return {
    props: { user, posts },
  };
}

export default function PostPage({ user, posts }) {
  return (
    <>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar sticky={false} />
        <UserProfile user={user} />
        <h1 className="user-books">Rezerwacje</h1>
        <PostFeed posts={posts} />
        <Navbar sticky={true} />
      </main>
    </>
  );
}
