import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Card from "../components/Card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        className={styles.banner}
        alt=""
        width={"100%"}
        height={"100%"}
        src="/banner.jpg"
      />
      <Navbar sticky={true} />
      <div className={styles.space}></div>
      {/* <img alt="" src="/banner.jpg" /> */}
      <Card
        direction="left"
        image="/banner.jpg"
        content="      Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, mollitia. Aut perspiciatis, minima eaque fuga ea veritatis fugiat consequatur nesciunt in cumque beatae? Non unde laboriosam quis error vitae nemo.
"
        page="/Pokoje"
      />
      <Card
        direction="right"
        image="/banner.jpg"
        content="      Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, mollitia. Aut perspiciatis, minima eaque fuga ea veritatis fugiat consequatur nesciunt in cumque beatae? Non unde laboriosam quis error vitae nemo.
"
        page="/Pokoje"
      />
      <Card
        direction="left"
        image="/banner.jpg"
        content="      Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, mollitia. Aut perspiciatis, minima eaque fuga ea veritatis fugiat consequatur nesciunt in cumque beatae? Non unde laboriosam quis error vitae nemo.
"
        page="/Pokoje"
      />
      <Card
        direction="right"
        image="/banner.jpg"
        content="      Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, mollitia. Aut perspiciatis, minima eaque fuga ea veritatis fugiat consequatur nesciunt in cumque beatae? Non unde laboriosam quis error vitae nemo.
"
        page="/Pokoje"
      />
      <Navbar sticky={false} />
      <Footer />
    </>
  );
}
