import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Kontakt.module.css";
import Image from "next/image";

export default function Book() {
  return (
    <>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        className="banner"
        alt=""
        src="/home.jpg"
        width={1920}
        height={860}
        priority={false}
      />
      <Navbar sticky={false} />
      <div className={styles.space}></div>
      <h1 className={styles.header}>Dane Kontaktowe</h1>
      <div className={styles.container}>
        <h2 className={styles.prawo}>Nr. telefonu: </h2>
        <p className={styles.rozmiar}>123 456 789</p>
        <h2 className={styles.prawo}>Adres E-Mail: </h2>
        <p className={styles.rozmiar}>info@hotelatreus.pl</p>
        <h2 className={styles.prawo}>Ulica: </h2>
        <p className={styles.rozmiar}>Wypoczynkowa 4</p>
        <h2 className={styles.prawo}>Miasto: </h2>
        <p className={styles.rozmiar}>Szklarska Poręba</p>
        <h2 className={styles.prawo}>Recepcja: </h2>
        <p className={styles.rozmiar}>recepcja@hotelatreus.pl</p>
        <h2 className={styles.prawo}>Recepcja tel.: </h2>
        <p className={styles.rozmiar}>112 345 678</p>
      </div>
      <Navbar sticky={true} />
      <Footer />
    </>
  );
}
