import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Oferta.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Section from "../components/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        className="banner"
        alt=""
        src="https://images.pexels.com/photos/618833/pexels-photo-618833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
      />
      <Navbar sticky={false} />
      <div className="space"></div>
      <Section
        direction={"left"}
        image={""}
        name={"Pakiet Małżeński"}
        price={"500zł/osobę za noc"}
        size={"Zawiera pokój małżeński, śniadanie, obiadokolacja"}
        content={""}
      />
      <Navbar sticky={true} color={""} />
      <Footer />
    </>
  );
}
