import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Rezerwacja.module.css";
import Calendar from "react-calendar";
import { useState, useEffect } from "react";
import "react-calendar/dist/Calendar.css";
import "react-hot-toast";
import Link from "next/link";
import toast from "react-hot-toast";

export default function Book() {
  const [przyjazd, setPrzyjazd] = useState(new Date());
  const [wyjazd, setWyjazd] = useState(new Date());
  const [prawidlowaData, setPrawidlowaData] = useState(true);
  const [radio, setRadio] = useState(true);

  useEffect(() => {
    if (przyjazd >= wyjazd) setPrawidlowaData(false);
    else setPrawidlowaData(true);
  }, [przyjazd, wyjazd]);

  const notify = () => {
    if (!prawidlowaData) {
      toast.error("wybierz prawidłową datę");
    }
  };

  return (
    <>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        className="banner"
        alt=""
        src="https://images.unsplash.com/photo-1621293954908-907159247fc8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
      />
      <Navbar sticky={false} />
      <div className="space"></div>
      <form>
        <div className={styles.rezerwacja}>
          <label htmlFor="od">Data przyjazdu:</label>
          <input
            type="text"
            name="od"
            id="od"
            className={styles.center_input}
            disabled
            value={przyjazd.toLocaleDateString("pl", {
              weekday: "long",
              year: "numeric",
              month: "short",
              day: "numeric",
            })}
          />
          <label htmlFor="do">Data wyjazdu:</label>
          <input
            type="text"
            name="od"
            id="od"
            className={styles.center_input}
            disabled
            value={wyjazd.toLocaleDateString("pl", {
              weekday: "long",
              year: "numeric",
              month: "short",
              day: "numeric",
            })}
          />
        </div>
        <div className={styles.kalendarze}>
          <Calendar onChange={setPrzyjazd} value={przyjazd} />
          <Calendar onChange={setWyjazd} value={wyjazd} />
        </div>

        <h1>Wybierz typ rezerwacji</h1>
        <div className={styles.pokoje}>
          <label htmlFor="typ">Pokój</label>
          <input
            type="radio"
            name="typ"
            id="typ"
            value={"Pokój"}
            onClick={() => setRadio(true)}
          />
          <span> </span>
          <label htmlFor="typ">Pakiet</label>
          <input
            type="radio"
            name="typ"
            id="typ"
            value={"Pakiet"}
            onClick={() => setRadio(false)}
          />
          <span></span>
          <select
            name="pokoj"
            id="pokoj"
            disabled={!radio}
            className={styles.lista}
          >
            <option id="1" value="">
              --wybierz pokój--
            </option>
            <option id="2" value={400}>
              Małżeński
            </option>
            <option id="3" value="350">
              Rodzinny
            </option>
          </select>
          <span></span>
          <span></span>
          <select
            name="pakiet"
            id="pakiet"
            disabled={radio}
            className={styles.lista}
          >
            <option id="1p" value="">
              --wybierz pakiet--
            </option>
            <option id="2p" value="470">
              Pakiet Małżeński z Pełnym Wyżywieniem
            </option>
            <option id="3p" value="440">
              Pakiet Małżeński ze Śniadaniem
            </option>
            <option id="4p" value="420">
              Pakiet Rodzinny z Pełnym Wyżywieniem
            </option>
            <option id="5p" value="385">
              Pakiet Rodzinny ze Śniadaniem
            </option>
            <option id="6p" value="495">
              Pakiet Ski Holidays
            </option>
          </select>
        </div>

        <h1>Wypełnij dane</h1>
        <div className={styles.dane}>
          <input
            required
            type="text"
            name="noce"
            id="noce"
            placeholder="Ilość nocy"
          />
          <input
            required
            type="text"
            name="osoby"
            id="osoby"
            placeholder="Ilośc osób"
          />
          <input
            required
            type="text"
            name="name"
            id="name"
            placeholder="Imię i nazwisko"
          />
          <input
            required
            type="text"
            name="mail"
            id="mail"
            placeholder="Adres e-mail"
          />
          <input
            required
            type="text"
            name="tel"
            id="tel"
            placeholder="Numer telefonu"
          />
          <input
            required
            type="text"
            name="ulica"
            id="ulica"
            placeholder="Ulica"
          />
          <input
            required
            type="text"
            name="zipcode"
            id="zipcode"
            placeholder="Kod pocztowy"
          />
          <input
            required
            type="text"
            name="city"
            id="city"
            placeholder="Miasto"
          />
        </div>

        <div className={styles.submit_cont} onMouseEnter={() => notify()}>
          <Link href={"/End"}>
            <button disabled={!prawidlowaData} className={styles.submit}>
              ZAREZERWUJ
            </button>
          </Link>
        </div>
      </form>
      <Navbar sticky={true} />
      <Footer />
    </>
  );
}
