import { auth, firestore, googleAuthProvider } from "../lib/firebase";
import {
  doc,
  writeBatch,
  getDoc,
  getFirestore,
  getCountFromServer,
} from "firebase/firestore";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Rezerwacja.module.css";
import Calendar from "react-calendar";
import { useState, useEffect, useContext } from "react";
import "react-calendar/dist/Calendar.css";
import "react-hot-toast";
import Link from "next/link";
import toast from "react-hot-toast";
import { UserContext } from "../lib/context";
import AuthCheck from "../components/AuthCheck";

export default function Book() {
  const [przyjazd, setPrzyjazd] = useState(new Date());
  const [wyjazd, setWyjazd] = useState(new Date());
  const [prawidlowaData, setPrawidlowaData] = useState(true);
  const [radio, setRadio] = useState(true);
  const [pokoj, setPokoj] = useState("");
  const [noce, setNoce] = useState(0);
  const [osoby, setOsoby] = useState(0);
  const [imieNazwisko, setImieNazwisko] = useState("");
  const [mail, setMail] = useState("");
  const [tel, setTel] = useState(0);
  const [ulica, setUlica] = useState("");
  const [zip, setZip] = useState("");
  const [miasto, setMiasto] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();

    const Doc = doc(
      getFirestore(),
      "users",
      auth.currentUser.uid,
      "Rezerwacje"
    );
    const snapshot = await getCountFromServer(Doc);
    const count = snapshot.data().count;
    const userDoc = doc(
      getFirestore(),
      "users",
      auth.currentUser.uid,
      "Rezerwacje",
      `Rezerwacja ${count}`
    );
    const batch = writeBatch(getFirestore());
    const content = {
      "Data przyjazdu": przyjazd,
      "Data wyjazdu": wyjazd,
      "Pokój/Pakiet": pokoj,
      "Ilość nocy": noce,
      "Ilość osób": osoby,
      "Imię i nazwisko": imieNazwisko,
      "E-Mail": mail,
      "Nr. Telefonu": tel,
      Ulica: ulica,
      "Kod pocztowy": zip,
      Miasto: miasto,
    };
    batch.set(userDoc, content);
    await batch.commit();
    toast.success("Rezerwacja udana. Dziękujemy za zaufanie!");
  };

  useEffect(() => {
    if (przyjazd >= wyjazd) setPrawidlowaData(false);
    else setPrawidlowaData(true);
  }, [przyjazd, wyjazd]);

  const notify = () => {
    if (!prawidlowaData) {
      toast.error("wybierz prawidłową datę");
    }
  };

  return (
    <AuthCheck>
      <Head>
        <title>Hotel Atreus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        className="banner"
        alt=""
        src="https://images.unsplash.com/photo-1621293954908-907159247fc8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
      />
      <Navbar sticky={false} />
      <div className="space"></div>
      <form onSubmit={handleSubmit}>
        <div className={styles.rezerwacja}>
          <label htmlFor="od">Data przyjazdu:</label>
          <input
            type="text"
            name="od"
            id="od"
            className={styles.center_input}
            disabled
            value={przyjazd.toLocaleDateString("pl", {
              weekday: "long",
              year: "numeric",
              month: "short",
              day: "numeric",
            })}
          />
          <label htmlFor="do">Data wyjazdu:</label>
          <input
            type="text"
            name="od"
            id="od"
            className={styles.center_input}
            disabled
            value={wyjazd.toLocaleDateString("pl", {
              weekday: "long",
              year: "numeric",
              month: "short",
              day: "numeric",
            })}
          />
        </div>
        <div className={styles.kalendarze}>
          <Calendar onChange={setPrzyjazd} value={przyjazd} />
          <Calendar onChange={setWyjazd} value={wyjazd} />
        </div>

        <h1 className={styles.naglowek}>Wybierz typ rezerwacji</h1>
        <div className={styles.pokoje}>
          <label htmlFor="typ">Pokój</label>
          <input
            required={true}
            type="radio"
            name="typ"
            id="typ"
            value={"Pokój"}
            onClick={() => setRadio(true)}
          />
          <span> </span>
          <label htmlFor="typ">Pakiet</label>
          <input
            required={true}
            type="radio"
            name="typ"
            id="typ"
            value={"Pakiet"}
            onClick={() => setRadio(false)}
          />
          <span></span>
          <select
            required={true}
            name="pokoj"
            id="pokoj"
            disabled={!radio}
            className={styles.lista}
            onChange={(e) => setPokoj(e.target.value)}
          >
            <option id="1" value="">
              --wybierz pokój--
            </option>
            <option id="2" value={400}>
              Małżeński
            </option>
            <option id="3" value="350">
              Rodzinny
            </option>
          </select>
          <span></span>
          <span></span>
          <select
            required={true}
            name="pakiet"
            id="pakiet"
            disabled={radio}
            className={styles.lista}
            onChange={(e) => setPokoj(e.target.value)}
          >
            <option id="1p" value="">
              --wybierz pakiet--
            </option>
            <option id="2p" value="470">
              Pakiet Małżeński z Pełnym Wyżywieniem
            </option>
            <option id="3p" value="440">
              Pakiet Małżeński ze Śniadaniem
            </option>
            <option id="4p" value="420">
              Pakiet Rodzinny z Pełnym Wyżywieniem
            </option>
            <option id="5p" value="385">
              Pakiet Rodzinny ze Śniadaniem
            </option>
            <option id="6p" value="495">
              Pakiet Ski Holidays
            </option>
          </select>
        </div>

        <h1 className={styles.naglowek}>Wypełnij dane</h1>
        <div className={styles.dane}>
          <input
            required={true}
            type="number"
            name="noce"
            id="noce"
            placeholder="Ilość nocy"
            onChange={(e) => setNoce(e.target.value)}
          />
          <input
            required={true}
            type="number"
            name="osoby"
            id="osoby"
            placeholder="Ilośc osób"
            onChange={(e) => setOsoby(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="name"
            id="name"
            placeholder="Imię i nazwisko"
            onChange={(e) => setImieNazwisko(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="mail"
            id="mail"
            placeholder="Adres e-mail"
            onChange={(e) => setMail(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="tel"
            id="tel"
            placeholder="Numer telefonu"
            onChange={(e) => setTel(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="ulica"
            id="ulica"
            placeholder="Ulica"
            onChange={(e) => setUlica(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="zipcode"
            id="zipcode"
            placeholder="Kod pocztowy"
            onChange={(e) => setZip(e.target.value)}
          />
          <input
            required={true}
            type="text"
            name="city"
            id="city"
            placeholder="Miasto"
            onChange={(e) => setMiasto(e.target.value)}
          />
        </div>

        <div className={styles.submit_cont} onMouseEnter={() => notify()}>
          <input
            type="submit"
            disabled={!prawidlowaData}
            className={styles.submit}
            value="ZAREZERWUJ"
          />{" "}
        </div>
      </form>
      <Navbar sticky={true} />
      <Footer />
    </AuthCheck>
  );
}
